config/routes.rb
Rails.application.routes.draw do

  resources :votes do
    collection do
      get 'list_candidates'
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def index
    @votes = Vote.group(:campaign_name).where.not(:validity => nil, :candidate_name => nil)
    @compaigns = @votes.map{|x| x.campaign_name} if @votes
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @compaigns }
    end
  end

  def list_candidates
    if params[:name]
      @candidate_details = []
      candidate_list = Vote.where(campaign_name: params[:name]).group(:candidate_name).map{|cd| cd.candidate_name}
      if candidate_list
        candidate_list.each do |cd|
          @cd_list = {}
          @cd_list["score"] = @cd_list["wrong_score"] = 0
          @cd_list["name"] = cd
          ## checking with validity during to count the candidate score
          result_with_score = Vote.where(campaign_name: params[:name], validity: "during", :candidate_name => cd).count
          @cd_list["score"] = result_with_score if result_with_score
          ## check for pre and post message on validity to define wrong score for candidate
          result_with_invalid_score = Vote.where(campaign_name: params[:name], :candidate_name => cd).where.not(validity: "during").count
          @cd_list["wrong_score"] = result_with_invalid_score if result_with_invalid_score
          @candidate_details << @cd_list
        end
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidate_details }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compaign</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/votes/index.html.erb
<table>
  <tr>
    <th>Compaign Name &nbsp; &nbsp; &nbsp;</th>
  </tr>

   <% @compaigns.each do |name| %>
  <tr>
    <td><%= link_to name, list_candidates_votes_path(:name => name)%></td>
  </tr>
  <% end %>

</table>

app/views/votes/list_candidates.html.erb
<%#= @arr_list %>

<table>
  <tr>
    <th>Candidates Name &nbsp; &nbsp; &nbsp;</th>
    <th>Candidates Score &nbsp; &nbsp; &nbsp;</th>
    <th>Candidates Wrong Score &nbsp; &nbsp; &nbsp;</th>
  </tr>

  <% @candidate_details.each do |cd_list| %>
    <tr>
      <td><%= cd_list["name"]%></td>
      <td><%= cd_list["score"]%></td>
      <td><%= cd_list["wrong_score"]%></td>
    </tr>
  <% end %>

</table>